version: "3.7"

services:
  database_ignite:
    image: postgres
    container_name: db_delivery
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=db_delivery
